### ISSUE TITLE
Замечания

### ISSUE THREAD

**Issue by vkats-spbu** [st129351/LabWork1#1]
Повороты работают неправильно. См. результат теста [rotations.zip](https://github.com/user-attachments/files/18188433/rotations.zip)

**Comment by lichkovahadaniil** [comment]
> Повороты работают неправильно. См. результат теста [rotations.zip](https://github.com/user-attachments/files/18188433/rotations.zip)

здравствуйте! все поправил, можете проверять, теперь повороты должны работать корректно.

**Comment by vkats-spbu** [comment]
Ситуация не изменилась

**Comment by lichkovahadaniil** [comment]
> Ситуация не изменилась

Теперь должна измениться, поправил

**Comment by AndreyIsakov01** [comment]
поворот не работает
<img width="1004" alt="image" src="https://github.com/user-attachments/assets/a8e9be2c-c0cc-4df2-bfb9-21888725b75a" />

**Comment by lichkovahadaniil** [comment]
> поворот не работает <img alt="image" width="1004" src="https://private-user-images.githubusercontent.com/73563875/397565244-a8e9be2c-c0cc-4df2-bfb9-21888725b75a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQ2NjY4OTksIm5iZiI6MTczNDY2NjU5OSwicGF0aCI6Ii83MzU2Mzg3NS8zOTc1NjUyNDQtYThlOWJlMmMtYzBjYy00ZGYyLWJmYjktMjE4ODg3MjViNzVhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjIwVDAzNDk1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJmNWY4YWI4NWE1YzA3MmQ1YWQzNDVjZjUzOTkxZWJhNzc2OGY5OWQxOWQ5NmM4N2I4YTcwMGYxMmVkNTNiMDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.kL1JZduH3Imy0ggrp5Tp2Z6AcKT7f_OrKZuf8wRmukA">

я сделал, сейчас должно работать, проверьте, пожалуйста
